// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_uNqp94oC49Rz58cBi0AxVwrMSQUYqE',
    appId: '1:682899753327:web:529add4cf7c1d45ddb809a',
    messagingSenderId: '682899753327',
    projectId: 'sportshub-d44ef',
    authDomain: 'sportshub-d44ef.firebaseapp.com',
    databaseURL: 'https://sportshub-d44ef-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-d44ef.firebasestorage.app',
    measurementId: 'G-SZ3BMHPLC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqghs8GRuLtb5j2IfwLzPcdgNoeqHSDq4',
    appId: '1:682899753327:android:dd5f852419624d77db809a',
    messagingSenderId: '682899753327',
    projectId: 'sportshub-d44ef',
    databaseURL: 'https://sportshub-d44ef-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-d44ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3MVjJEv8U2Kvs8ZcoSekziI8e8kO5kGM',
    appId: '1:682899753327:ios:5c01b28b5ed6dee3db809a',
    messagingSenderId: '682899753327',
    projectId: 'sportshub-d44ef',
    databaseURL: 'https://sportshub-d44ef-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-d44ef.firebasestorage.app',
    iosBundleId: 'com.example.sportsmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3MVjJEv8U2Kvs8ZcoSekziI8e8kO5kGM',
    appId: '1:682899753327:ios:5c01b28b5ed6dee3db809a',
    messagingSenderId: '682899753327',
    projectId: 'sportshub-d44ef',
    databaseURL: 'https://sportshub-d44ef-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-d44ef.firebasestorage.app',
    iosBundleId: 'com.example.sportsmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_uNqp94oC49Rz58cBi0AxVwrMSQUYqE',
    appId: '1:682899753327:web:5d5093606fd3277adb809a',
    messagingSenderId: '682899753327',
    projectId: 'sportshub-d44ef',
    authDomain: 'sportshub-d44ef.firebaseapp.com',
    databaseURL: 'https://sportshub-d44ef-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-d44ef.firebasestorage.app',
    measurementId: 'G-5JQCVZJXKE',
  );

}